# docker-compose.yml
version: '3.8'
services:
    db:
        image: postgres:16-alpine # Lightweight PostgreSQL image
        restart: always
        ports:
            - '5432:5432' # Host:Container
        environment:
            POSTGRES_DB: myproject_dev
            POSTGRES_USER: devuser
            POSTGRES_PASSWORD: devpassword
        volumes:
            - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
    postgres_data:
